In [1]:
import numpy as np
np.ones((4,4))



array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [2]:
np.full(shape=(4,4),fill_value = 8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [3]:
def A():
    input1  = 'my name is shubham'
    s= input1.split()
    l1= []
    for i in s:
        k = ((i[::-1]).capitalize())
        l1.append(k)
#print(l1)
    a = ' '.join(l1)
    return (a)
    
A()

'Ym Eman Si Mahbuhs'

In [4]:
np.full(shape=(4,4),fill_value = 'i love you')

array([['i love you', 'i love you', 'i love you', 'i love you'],
       ['i love you', 'i love you', 'i love you', 'i love you'],
       ['i love you', 'i love you', 'i love you', 'i love you'],
       ['i love you', 'i love you', 'i love you', 'i love you']],
      dtype='<U10')

In [5]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array set

In [6]:
np_array = np.array([3,5,6,'NAAs'])

In [7]:
np_array

array(['3', '5', '6', 'NAAs'], dtype='<U11')

In [8]:
np.random.seed(8)
np.random.rand(3,3,3)

array([[[0.8734294 , 0.96854066, 0.86919454],
        [0.53085569, 0.23272833, 0.0113988 ],
        [0.43046882, 0.40235136, 0.52267467]],

       [[0.4783918 , 0.55535647, 0.54338602],
        [0.76089558, 0.71237457, 0.6196821 ],
        [0.42609177, 0.28907503, 0.97385524]],

       [[0.33377405, 0.21880106, 0.06580839],
        [0.98287055, 0.12785571, 0.32213079],
        [0.07094284, 0.22476994, 0.39363491]]])

In [9]:
np.random(5)


TypeError: 'module' object is not callable

In [ ]:
np.random.randint(low =0, high = 8, size = (3,3))

In [ ]:
np.random.randint(0,9,(3,3))


In [ ]:
a = np.arange(6,60,5)

In [ ]:
a.size

In [ ]:
a = np.arange(4,41,4)

In [ ]:
a

In [ ]:
(np.arange(1,11))*4


# 16/06/21 Data Wrangling

In [10]:
b= np.random.rand(3,4,5,6)

In [11]:
b.ndim

4

In [12]:
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [26]:
a = np.random.randint(1,8,(3,3,3))

array([[[5, 4, 4],
        [1, 5, 4],
        [1, 3, 3]],

       [[7, 4, 6],
        [3, 4, 6],
        [5, 5, 6]],

       [[1, 7, 7],
        [6, 7, 6],
        [5, 4, 2]]])

In [23]:
np.random.seed(7)
x = np.random.randint(0,100,(10,10))


In [24]:
x.max()

99

In [25]:
x.min()

0

In [30]:
vector = np.array([25,40,88,40,100])

In [31]:
vector

array([ 25,  40,  88,  40, 100])

In [40]:
# create matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

matrix[0:2,:]



array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
matrix[:,0:1]

array([[1],
       [4],
       [7]])

In [43]:
a = np.array([1,2,0,0,4,0])
a[a>0]

array([1, 2, 4])

# image processing using numpy