In [3]:
import numpy as np

In [5]:
matrix = np.array([[7,8,9],
                 [5,2,6],
                 [8,5,6]])

In [6]:
np.linalg.det(matrix)

98.99999999999999

In [7]:
matrix.T  #transpose matrix

array([[7, 5, 8],
       [8, 2, 5],
       [9, 6, 6]])

In [9]:
m_a = np.array([[1,2],
                [2,1]])

m_b = np.array([[2,1],
               [1,2]])

In [10]:
np.dot(m_a,m_b)

array([[4, 5],
       [5, 4]])

In [12]:
m = np.array([[2,3],
             [2,4]])

In [13]:
np.linalg.inv(m)

array([[ 2. , -1.5],
       [-1. ,  1. ]])